platform: linux

image_resource:
    type: docker-image
    source: {repository: busybox, tag: latest}

inputs:
    - name: git-rokas-test
    - name: prune-info

params:
    channel: "#uk-cec-concourse-team-automation"

run:
    path: sh
    args:
    - -exc
    - |
        chmod +x ./git-rokas-test/scripts/slack_message.sh
        ./git-rokas-test/scripts/slack_message.sh