---
platform: linux

image_resource:
    type: docker-image
    source: {repository: ubuntu, tag: latest}

inputs:
    - name: git-rokas-test

run:
    path: sh
    args:
    - -exc
    - |
        chmod +x ./git-rokas-test/scripts/helloworld.sh
        ./git-rokas-test/scripts/helloworld.sh
