---
platform: linux

image_resource:
    type: docker-image
    source: {repository: ubuntu, tag: latest}

inputs:
    - name: rokas-test

run:
    path: sh
    args:
    - -exc
    - |
        chmod +x ./rokas-test/scripts/helloworld.sh
        ./rokas-test/scripts/helloworld.sh
