---
resources:
  - name: rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev

jobs:
  - task: shell-task
    file: rokas-test/tasks/workers.yml
    params: 
      oncourse_user_secret: ((concourse_local_password))
        


