---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: git-rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev
  - name: notify
    type: slack-notification
    source:
      url: ((slack_webhook_concours_aws_sso))
  - name: every-hour
    type: time
    icon: clock-outline
    source:
      interval: 60m

jobs:
  - name: check_workers
    plan:
      - get: every-hour
        trigger: true
      - get: git-rokas-test
      - task: shell-task
        file: git-rokas-test/tasks/workers.yml
        params: 
          concourse_user_secret: ((concourse_local_password))
        on_failure:
          put: notify
          params: 
            text_file: prune-info/file
            channel: "#uk-cec-concourse-prod"
          

      

