---
resources:
  - name: rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev

jobs:
  - name: shell-job
    - task: fly_commands
      file: test/tasks/workers.yml
      params: 
        concourse_user_secret: ((concourse_local_password))
