---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: git-rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev
  - name: notify
    type: slack-notification
    source:
      url: ((uk-cec-concourse-prod-slack-webhook-url))
  - name: every-hour
    type: time
    icon: clock-outline
    source:
      interval: 1h
    check_every: 1h

jobs:
  - name: check_workers
    plan:
      - get: every-hour
        trigger: true
      - get: git-rokas-test
      - task: shell-task
        file: git-rokas-test/tasks/workers.yml
        params: 
          concourse_url: https://concourse.at.sky
          concourse_user_secret: ((concourse_local_password))
          access_key_id: ((concourse_prod_aws_access_key_id))
          secret_access_key: ((concourse_prod_aws_secret_access_key))
          aws_default_region: eu-west-1
        on_success:
          put: notify
          params: 
            text_file: prune-info/pruned.txt
            channel: "#uk-cec-concourse-prod"
            

        on_failure:
          put: notify
          params: 
            text_file: prune-info/pruned.txt
            channel: "#uk-cec-concourse-prod"
            

      

      

