---
resources:
  - name: git-rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev

jobs:
  - name: check_workers
    plan:
      - get: git-rokas-test
      - task: shell-task
        file: git-rokas-test/tasks/workers.yml
        params: 
          concourse_user_secret: ((concourse_local_password))
        


