---
resources:
  - name: rokas-test
    type: git
    source:
      uri: https://github.com/rockyvisockis/test.git
      branch: dev

jobs:
  - name: shell-job
    public: true
    plan:
      - get: rokas-test
      - task: run-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}

          inputs:
            - name: rokas-test

          run:
            params: 
              concourse_user_secret: ((concourse_local_password))
            path: rokas-test/scripts/helloworld.sh



